### ISSUE TITLE
Code is broken on several counts

### ISSUE THREAD

**Issue by asarkar** [bijukunjummen/spring-cloud-ping-pong-sample#2]
Hi,
I came across your blog and subsequently, the code, looking for examples of Spring cloud Netflix. Unlike you, I'm using Gradle and traditional war deployment (not repackaged jar by boot). Still out of curiosity, I cloned this repo and tried to bring up the apps. In doing so, I found several issues:
1. `docker-compose.yml` doesn't have a `name` attribute. At least, not the version I've installed, v1.5.1. Perhaps you're using an older one. The attribute you may be looking for is [container_name](https://docs.docker.com/compose/compose-file/#container-name) even though using a fixed name means you can't scale it beyond a single instance.
2. The tests fail out of the box looking for Eureka.
3. `link` in `docker-compose.yml` is discouraged and will not be supported in near future. You may want to use [--x-networking](https://docs.docker.com/compose/networking) option.
4. Fixing issue 1 and running `docker-compose up` fails due to port conflict. I've not looked into it but it seems you're instanting Eureka from both ping and pong on the same port. I'm not sure why do you need `eureka.instance. nonSecurePort` property in your `bootstrap.yml`. I'm still cutting my teeth on Spring Cloud so please educate me if I'm missing something.

```
ERROR: Cannot start container xxx: failed to create endpoint springcloudpingpongsample_sampleping_1 on network springcloudpingpongsample: Bind for 0.0.0.0:8080 failed: port is already allocated
```

I've my own problems with Gradle and traditional war deployment because no one else seems to have done it, at least not that I could find yet. Everyone is running the embedded Tomcat with boot. That's fine for examples but when you need common Tomcat configurations like I do (admin user, port etc), that's not a feasible solution. I've an [SO question](http://stackoverflow.com/questions/34471032/eureka-server-not-accessible-for-traditional-war-deployment-in-docker) out, if you're interested, take a look.

Regards,
Abhijit

**Comment by bijukunjummen** [comment]
Thanks for your feedback Abhijit. You are right, it is broken for newer versions of docker-compose (1.5.0+), I have now cleaned it up by removing the name attribute and it appears to start up cleanly now. I did not see any issues with link being used in docker-compose though and see that `--x-networking` is an experimental feature, I will keep an eye on it and will move to it when it is released. 

You are right about the tests also, all of them are integration tests, so there is no real point to them without a full integration env, I have removed them for now.

Otherwise, it starts up cleanly for me without any port conflicts. The UI should be available at `http://dockerhost:8080`, not sure why you would be seeing issues locally.

Regarding your SO question, I see that you have already got an answer.

**Comment by asarkar** [comment]
Thank you for getting to it so quickly. The deprecation of `link` is mentioned [here](https://docs.docker.com/compose/networking). For your convenience, I quote:

> Docker links are a one-way, single-host communication system. They should now be considered deprecated, and you should update your app to use networking instead. 

The reason, as I understand, is that links only work on the same host and using `--x-networking` puts all the containers in the same network so links are not necessary.
That said, the default Eureka configuration doesn't play well with docker compose's hostnames. There's some discussion on how to work around that [here](https://github.com/spring-cloud/spring-cloud-netflix/issues/432) that I've not tried due to lack of time. I'm just using the docker machine IP in `docker-compose.yml` for now.

I've come across your blog time to time and it seems that we're pursuing similar interests (Java, Scala, Docker).

Regards,
Abhijit

**Comment by asarkar** [comment]
Verified that it now works as expected.
